# Deploy to these servers.
servers:
  - 216.128.176.23

# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
env:
  clear:
    RAILS_ENV: staging
  secret:
    - RAILS_MASTER_KEY
    - APPSIGNAL_PUSH_API_KEY
