# Deploy to these servers.
servers:
  - 216.128.176.23

# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
env:
  clear:
    RAILS_ENV: staging
    LITESTREAM_ENABLED: true
  secret:
    - APP_HOST
    - RAILS_MASTER_KEY
    - POSTMARK_API_TOKEN
    - LITESTREAM_BUCKET
    - LITESTREAM_ACCESS_KEY_ID
    - LITESTREAM_SECRET_ACCESS_KEY
    - APPSIGNAL_ORG_PUSH_API_KEY
    - APPSIGNAL_APP_PUSH_API_KEY
